'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18010
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class keywordColored
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Luna.keywordColored", GetType(keywordColored).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to using,namespace,public,enum,partial,class,static,get,set,if,null,try,catch,Exception,int,abstract,void,Err,bool,virtual,protected,string, Empty,region,endregion,.
        '''</summary>
        Friend Shared ReadOnly Property KeywordCSharp() As String
            Get
                Return ResourceManager.GetString("KeywordCSharp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE,ALTER,TABLE,COLUMN,ADD,INT,COUNTER,LONG,DATETIME,TEXT,DROP,INDEX,PRIMARY,(,),MEMO,NOT,NULL,WITH,ON,YESNO,SINGLE,DOUBLE.
        '''</summary>
        Friend Shared ReadOnly Property KeywordSQL() As String
            Get
                Return ResourceManager.GetString("KeywordSQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to if,then,else,imports,class,nothing,friend,public,private,dim,try,catch,as,end,datetime,integer,string,Elseif,TypeOf,boolean,#Region,#end region,private,get,set,return,property,function,sub,new,is,not,byref,byval,single,long,bit,optional,while,MustInherit,Inherits,Protected,Shared,For,Each,Next,List(Of,Namespace,Partial,Module,Implements.
        '''</summary>
        Friend Shared ReadOnly Property KeywordVB() As String
            Get
                Return ResourceManager.GetString("KeywordVB", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
